function [fitresult, gof] = createFit_gaussian(tc, eind, wb, x00)
%CREATEFIT1(TC,EIND,WB)
%  Create a fit.
%
%  Data for 'untitled fit 5' fit:
%      X Input : tc
%      Y Output: eind
%      Weights : wb
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 16-Mar-2022 15:41:06


%% Fit: 'untitled fit 5'.
[xData, yData, weights] = prepareCurveData( tc, eind, wb );

% Set up fittype and options.
ft = fittype( 'b + a*exp(-(x-x0).^2/sigma^2)', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = x00;
opts.Weights = weights;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
% figure( 'Name', 'untitled fit 5' );
% h = plot( fitresult, xData, yData );
% legend( h, 'eind vs. tc with wb', 'untitled fit 5', 'Location', 'NorthEast', 'Interpreter', 'none' );
% % Label axes
% xlabel( 'tc', 'Interpreter', 'none' );
% ylabel( 'eind', 'Interpreter', 'none' );
% grid on

end
