function [fitresult, gof] = createFit_square(tc, eind, wb, x00)
%CREATEFIT1(TC,EIND,WB)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : tc
%      Y Output: eind
%      Weights : wb
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 16-Mar-2022 17:21:29


%% Fit: 'untitled fit 1'.
[xData, yData, weights] = prepareCurveData( tc, eind, wb );

% Set up fittype and options.
ft = fittype( '- a - c*(heaviside(x - (x0 + sigma/2)) - heaviside(x - (x0-sigma/2)))', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [-0.5 0 0 -0.5];
opts.StartPoint = x00;
% opts.StartPoint = [0 1 0.5 -0.1];
opts.Upper = [0.5 4 1 0.5];
opts.Weights = weights*0 + 1;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
end


